upstream ms_parqueaderos_upstream {
    least_conn;
    server ms-parqueaderos-1:3003;
    server ms-parqueaderos-2:3003;
}

server {
    listen 5173;
    server_name localhost;

    # Balanceo de carga para DATOS de parqueaderos (Microservicio)
    location /parking/ {
        proxy_pass         http://ms_parqueaderos_upstream/v1/parqueaderos/;
        proxy_http_version 1.1;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Authorization   $http_authorization;
        proxy_pass_header  Authorization;
    }

    # API Gateway — Proxy a las demás rutas de la API
    location /api/ {
        proxy_pass         http://gateway:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Authorization   $http_authorization;
        proxy_pass_header  Authorization;
    }

    # Proxy para el FRONTEND (Vite / SSR server)
    # Esto permite que Nginx sirva el HTML y los assets delegando al contenedor frontend
    location / {
        proxy_pass         http://frontend:5173;
        proxy_http_version 1.1;
        proxy_set_header   Host            $host;
        proxy_set_header   X-Real-IP       $remote_addr;
        proxy_set_header   Upgrade         $http_upgrade;
        proxy_set_header   Connection      "upgrade";
    }
}
